### ISSUE TITLE
telegraf.influxdata.com/interval options does no work

### ISSUE THREAD

**Issue by vova3379** [influxdata/telegraf-operator#50]
Hello, we are using telegraf operator and telegraf sidecarimage versions below 
```
telegraf-operator:1.1.1
telegraf:1.14.2-alpine
```

annotation we added to the pod below 
```
                      telegraf.influxdata.com/inputs:
                        [[inputs.prometheus]]
                          urls = ["http://localhost:9153/metrics"]
                      telegraf.influxdata.com/interval: 30s
```

but interval parameter ignored and metrics collection goes with 10s default interval
config output from sidecar container
```
/ # cat etc/telegraf/telegraf.conf

[[inputs.internal]]

[[inputs.prometheus]]
  urls = ["http://localhost:9153/metrics"]

[[outputs.influxdb]]
  urls = ["http://dev.influxdb-data.service.consulzone:8086"]
  database = "infra-metrics"
  retention_policy = "7d"
[global_tags]
  cluster = "dev-general"
```

the influx also show metric collection every 10 seconds versus 30s. Can you suggest why interval parameter ignored?

**Comment by BondAnthony** [comment]
Hi @vova3379, sorry for the long delay and the issue you have experienced. I've run a few tests and here are my findings.

### Prometheus Scrape with Annotations
Users can use annotations to populate the Telegraf `input.prometheus` plugin. The example below will create a Telegraf sidecar to collect metrics in Prometheus exposition format. You can set the interval, path, port, scheme, and a few other settings.

**Annotations**
```
spec.template.metadata.annotations
        telegraf.influxdata.com/class: infra
        telegraf.influxdata.com/interval: 30s
        telegraf.influxdata.com/path: /metrics
        telegraf.influxdata.com/port: "8086"
        telegraf.influxdata.com/scheme: http
```

**Expected Input Configuration**
```
[[inputs.prometheus]]
  urls = ["http://127.0.0.1:8086/metrics"]
  interval = "30s"

[[inputs.internal]]

```

### Raw Input
When using the `telegraf.influxdata.com/inputs` annotation the user will need to add all the parameters for the specific input. We currently don't override any settings within these raw inputs. This allows for users to have a lot of control when it comes to these inputs. The annotation `telegraf.influxdata.com/interval` will only apply to the generated prometheus scrape input when `telegraf.influxdata.com/port` is set. In order to set the interval you would need the following annotation. The operator doesn't set global configurations based on annotations currently.

```
spec.template.metadata.annotations
        telegraf.influxdata.com/class: infra
        telegraf.influxdata.com/inputs: |
          [[inputs.prometheus]]
            urls = ["http://localhost:8086/metrics"]
            interval = "30s"
```

**Expected Input Configuration**
```

[[inputs.internal]]

[[inputs.prometheus]]
  urls = ["http://localhost:8086/metrics"]
  interval = "30s"

```

Please let me know if this helps and I'll open a PR to address the readme making this clear when it comes to annotations.

**Comment by vova3379** [comment]
Hi @BondAnthony thanks a lot for the help 
```
       [[inputs.prometheus]]
         urls = ["http://localhost:9153/metrics"]
        interval = "30s"
```
did the trick and we start collecting metrics with needed interval, closing issue.
